[package]
authors = ["Vadzim Dambrouski <pftbest@gmail.com>", "Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Low level access to MSP430 microcontrollers"
documentation = "https://docs.rs/msp430"
keywords = ["msp430", "interrupt", "register", "peripheral"]
license = "MIT OR Apache-2.0"
name = "msp430"
repository = "https://github.com/pftbest/msp430"
version = "0.1.0"

[dependencies.bare-metal]
features = ["const-fn"]
version = "0.2.0"
